### ISSUE TITLE
pixcols.csv doesn't appear to exist

### ISSUE THREAD

**Issue by cbritt4** [james-trayford/ifu-listener#10]
Hi James, 
In trying to get the ifu-listener up and running in the browser, I'm hitting an error that app.py is looking for a file "static/pixcols.csv", which doesn't appear to exist. I'm following the instructions in the "serving locally" section of the Readme.  https://github.com/james-trayford/ifu-listener/blob/170487c640b03fddafaf5ce6c0122ecf19c62eea/listener-app/app.py#L36
Any idea if I needed to install something else first in my environment that is missing? I did run 
> pip3 install -r requirements.txt

and it looks like everything completed properly. 

Cheers,
Chris

**Comment by james-trayford** [comment]
Hi Chris,

I think you've might have come across our initial experiment with the IFU listener instead of the JDAViz integrated version - this is based on Python Flask but we're now mostly focussing on the one built into JDAViz.

The development branch for sonification in jdaviz can be found here: https://github.com/james-trayford/jdaviz/tree/sonify-plugin-updates-jt 

There's a requirements file here (https://github.com/james-trayford/strauss_jdat_hack/blob/main/requirements_slim.txt) which will install the right versions of `strauss` and `jdaviz` - you can run this in e.g. a python virtual environment. 

once requirements are installed you shoulkd be able to run the version with sonification plug-in as:
```
from jdaviz import Cubeviz

uris = ["jw02016-c1009_t011_miri_ch1-shortmediumlong_s3d.fits", # NGC1052 - edge-on galaxy
       "jw02016-c1012_t023_miri_ch1-shortmediumlong_s3d.fits", # Sombrero Galaxy - edge-on galaxy
       "jw02732-o004_t004_miri_ch1-shortmediumlong_s3d.fits"] # NGC7319 - AGN


cubeviz.load_data(f"mast:JWST/product/{uris[0]}", override_cube_limit=True)
cubeviz.show()
```

RE this repo - I think some of the links to download initial data might be broken now - I can look at this - but my guess was that you might want the JDAViz version?

**Comment by cbritt4** [comment]
Hi James,
Thanks, I did want the jdaviz version. I got it working in its own environment now, thank you for your help.
Cheers,
Chris
